/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/tpay/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * web-get-token
         * @description **_Path_**
         *     /access-token
         *
         *
         *     **_Description_**
         *     Request access-token that should then be used to access Tpay resourses.
         *
         *
         *     **_Request Parameters_**
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **apikey** * _(header)_ | _string_ | developer app key value
         *     **client\_id** * _(body)_ | _string_ | tpay client_id (merchant id)
         *     **client\_secret** * _(body)_ | _string_ | client secret
         *
         *
         *     **_Response Model_**
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **access_token** | _string_ | access token value
         *     **token_type** | _string_ | type of the token is set to “Bearer”
         *     **expires_in** | _integer($int32)_ | lifetime in seconds of the access token
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/x-www-form-urlencoded */
                    "Content-Type"?: string;
                    /**
                     * @description Developer app key for making API calls through Open API platfrom.
                     * @example {{app-key}}
                     */
                    apikey?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /**
                         * @description TBC Checkout client_id (merchant id)
                         * @example {{web-client-id}}
                         */
                        client_id: string;
                        /**
                         * @description TBC Checkout client_secret
                         * @example {{web-client-secret}}
                         */
                        client_secret: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        Date?: string;
                        "Content-Type"?: string;
                        "Transfer-Encoding"?: string;
                        Connection?: string;
                        "Strict-Transport-Security"?: string;
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNDQkQzN0Q1Qjc2QTcyMTMzNTFFMTYzMDk1NDkyRjE4MTA3RkE1MEYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJQTDAzMWJkcWNoTTFIaFl3bFVrdkdCQl9wUTgifQ.eyJuYmYiOjE1NjUzNTkwNjcsImV4cCI6MTU2NTQ0NTQ2NywiaXNzIjoiaHR0cHM6Ly9hY2NvdW50c3RwYXl0c3QudGJjYmFuay5nZS8iLCJhdWQiOlsiaHR0cHM6Ly9hY2NvdW50c3RwYXl0c3QudGJjYmFuay5nZS9yZXNvdXJjZXMiLCJwYXltZW50YXBpIl0sImNsaWVudF9pZCI6IjUzOTk5OTkiLCJzY29wZSI6WyJwYXltZW50YXBpIl19.EG29V9wxjGPUpnJlYOcAcEYw9BvSiCFwqfzAbZ4jkxJD4q-EcP94-i7XLZhzS8Vv4k1NBWHg2x7MKQQu81AlBFungVCKFwNCV0ItkYPTSguq4s5QGpgQcSjtmC_q6wVTT8WA4jR7IcwQ8qZMKKcrAZJBehDWdal1uO_Mhnn1Dnc9KFdFnXWUc7iIjIryuHPc3U-ZOQh2COIl0Acl-LTMeRh_KZByz2Gf2lLShhRbI0G-5YtWXObtLZ2ZKfCJB50TtaMM16vrfSQXh0FX6BHHxAtyPBflOzCgovi8CORgkTbaGaPtJHqjfep8r8L-45zhFVPXT19rLhWyfhEPBDm78A",
                         *       "expires_in": 86400,
                         *       "token_type": "Bearer"
                         *     }
                         */
                        "application/json": {
                            access_token: string;
                            token_type: string;
                            expires_in: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tpay/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * web-create-payment
         * @description **_Path_**
         *     /payments
         *
         *
         *     **_Description_**
         *     Request initiates Tpay web payment. The response contains payment object details and links for a) checking payment status and b) redirecting user to finish initiated payment.
         *
         *
         *     **_Authorization_**
         *
         *     Bearer {_access-token value_}
         *
         *     **_Request Parameters_**
         *
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **apikey** * _(header)_ | _string_ | developer app key value
         *     **amount {}** * _(body)_ | _array_ | payment amount {}
         *     **-- currency** * | _string_ | currency of transaction
         *     **-- total** * | _number_ | total amount of payment
         *     **-- subtotal** | _number_ | amount of purchase
         *     **-- tax** | _number_ | amount of tax
         *     **-- shipping** | _number_ | amount of shipping price
         *     **returnurl** * _(body)_ | _string_ | callback url to redirect user after finishing payment (e.g."order details page")
         *     **extra** _(body)_ | _string_ | additional parameter for merchant-specific info
         *
         *
         *     **_Response Model_**
         *
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **payId** | _string_ | payment id
         *     **status** | _string_ | payment status / Created / Processing / Succeeded / Failed
         *     **links {}** | _array_ | links
         *     **-- uri** | _string_ | URL
         *     **-- method** | _string_ | method to use on URL
         *     **-- rel** | _string_ | action to use on URL
         *     **transactionId** | _string_ | transaction_id from UFC
         *     **httpStatusCode** | _string_ | http status code
         *     **developerMessage** | _string_ | developer message for logging in local system
         *     **userMessage** | _string_ | error message for user
         *
         *
         *
         *     >_httpStatusCode_ values:
         *     * 200 - finished successfully
         *     * 400 - bad request, incorrect parameters
         *     * 401 - request unauthorized
         *     * 500 - internal server error
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                    /** @example {{app-key}} */
                    apikey?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "amount": {
                     *         "currency": "GEL",
                     *         "total": 200,
                     *         "subTotal": 0,
                     *         "tax": 0,
                     *         "shipping": 0
                     *       },
                     *       "returnurl": "shopping.ge/callback",
                     *       "extra": "GE60TB7226145063300008",
                     *       "userIpAddress": "127.0.0.1",
                     *       "expirationMinutes": "5",
                     *       "methods": [
                     *         5,
                     *         7,
                     *         8
                     *       ],
                     *       "installmentProducts": [
                     *         {
                     *           "Name": "t1",
                     *           "Price": 100,
                     *           "Quantity": 1
                     *         },
                     *         {
                     *           "Name": "t1",
                     *           "Price": 50,
                     *           "Quantity": 1
                     *         },
                     *         {
                     *           "Name": "t1",
                     *           "Price": 50,
                     *           "Quantity": 1
                     *         }
                     *       ],
                     *       "callbackUrl": "https://google.com",
                     *       "preAuth": true,
                     *       "language": "EN",
                     *       "merchantPaymentId": "P123123",
                     *       "saveCard": true,
                     *       "saveCardToDate": "0321"
                     *     }
                     */
                    "application/json": {
                        amount: components["schemas"]["PaymentAmount"];
                        returnurl: string;
                        extra?: string;
                        userIpAddress?: string;
                        expirationMinutes?: string;
                        callbackUrl?: string;
                        merchantPaymentId?: string;
                        saveCardToDate?: string;
                        /** @enum {string} */
                        language?: "EN" | "KA";
                        methods?: number[];
                        installmentProducts?: {
                            Name?: string;
                            Price?: number;
                            Quantity?: number;
                        }[];
                        preAuth?: boolean;
                        saveCard?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        Date?: string;
                        "Content-Type"?: string;
                        "Transfer-Encoding"?: string;
                        Connection?: string;
                        "Strict-Transport-Security"?: string;
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "payId": "tpay-fkgokd18839",
                         *       "status": "Created",
                         *       "links": [
                         *         {
                         *           "uri": "https://tpaypaymentapi.test.loc:8079/v1/Payments/tpay-fkgokd18839",
                         *           "method": "GET",
                         *           "rel": "self"
                         *         },
                         *         {
                         *           "uri": "https://tpaycheckoutweb.test.loc:8078/checkout/tpay-fkgokd18839",
                         *           "method": "REDIRECT",
                         *           "rel": "approval_url"
                         *         }
                         *       ],
                         *       "transactionId": null,
                         *       "httpStatusCode": 200,
                         *       "developerMessage": null,
                         *       "userMessage": null
                         *     }
                         */
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tpay/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * web-get-payment
         * @description **_Path_**
         *     /payments/{payment_id}
         *
         *
         *     **_Description_**
         *     Request returns payment details for given payment_id
         *
         *
         *     **_Authorization_**
         *
         *     Bearer {_access-token value_}
         *
         *     **_Request Parameters_**
         *
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **apikey** * _(header)_ | _string_ | developer app key value
         *     **payment_id** * _(path)_ | _string_ | payment id
         *
         *
         *     **_Response Model_**
         *
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **payId** | _string_ | payment id
         *     **status** | _string_ | payment status / Created / Processing / Succeeded / Failed
         *     **links {}** | _array_ | links
         *     **-- uri** | _string_ | URL
         *     **-- method** | _string_ | method to use on URL
         *     **-- rel** | _string_ | action to use on URL
         *     **transactionId** | _string_ | transaction_id from UFC
         *     **httpStatusCode** | _string_ | http status code
         *     **developerMessage** | _string_ | developer message for logging in local system
         *     **userMessage** | _string_ | error message for user
         *
         *
         *
         *     >_httpStatusCode_ values:
         *     * 200 - finished successfully
         *     * 400 - bad request, incorrect parameters
         *     * 401 - request unauthorized
         *     * 500 - internal server error
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/x-www-form-urlencoded */
                    "Content-Type"?: string;
                    /** @example {{app-key}} */
                    apikey?: string;
                };
                path: {
                    /** @example {{payment-id}} */
                    payment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        Date?: string;
                        "Content-Type"?: string;
                        "Transfer-Encoding"?: string;
                        Connection?: string;
                        "Strict-Transport-Security"?: string;
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "payId": "tpay-fkgokd18839",
                         *       "status": "Created",
                         *       "links": null,
                         *       "transactionId": null,
                         *       "httpStatusCode": 200,
                         *       "developerMessage": null,
                         *       "userMessage": null
                         *     }
                         */
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tpay/payments/{payment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * web-cancel-payment
         * @description **_Path_**
         *     /payments
         *
         *
         *     **_Description_**
         *     Request initiates Tpay web payment. The response contains payment object details and links for a) checking payment status and b) redirecting user to finish initiated payment.
         *
         *
         *     **_Authorization_**
         *
         *     Bearer {_access-token value_}
         *
         *     **_Request Parameters_**
         *
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **apikey** * _(header)_ | _string_ | developer app key value
         *     **amount {}** * _(body)_ | _array_ | payment amount {}
         *     **-- currency** * | _string_ | currency of transaction
         *     **-- total** * | _number_ | total amount of payment
         *     **-- subtotal** | _number_ | amount of purchase
         *     **-- tax** | _number_ | amount of tax
         *     **-- shipping** | _number_ | amount of shipping price
         *     **returnurl** * _(body)_ | _string_ | callback url to redirect user after finishing payment (e.g."order details page")
         *     **extra** _(body)_ | _string_ | additional parameter for merchant-specific info
         *
         *
         *     **_Response Model_**
         *
         *
         *     Name | Type | Description
         *     ------------ | ------------- | ------------
         *     **payId** | _string_ | payment id
         *     **status** | _string_ | payment status / Created / Processing / Succeeded / Failed
         *     **links {}** | _array_ | links
         *     **-- uri** | _string_ | URL
         *     **-- method** | _string_ | method to use on URL
         *     **-- rel** | _string_ | action to use on URL
         *     **transactionId** | _string_ | transaction_id from UFC
         *     **httpStatusCode** | _string_ | http status code
         *     **developerMessage** | _string_ | developer message for logging in local system
         *     **userMessage** | _string_ | error message for user
         *
         *
         *
         *     >_httpStatusCode_ values:
         *     * 200 - finished successfully
         *     * 400 - bad request, incorrect parameters
         *     * 401 - request unauthorized
         *     * 500 - internal server error
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                    /** @example {{app-key}} */
                    apikey?: string;
                };
                path: {
                    /** @example {{payment-id}} */
                    payment_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "amount": 2
                     *     }
                     */
                    "application/json": {
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        Date?: string;
                        "Content-Type"?: string;
                        "Transfer-Encoding"?: string;
                        Connection?: string;
                        "Strict-Transport-Security"?: string;
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "payId": "tpay-fkgokd18839",
                         *       "status": "Created",
                         *       "links": [
                         *         {
                         *           "uri": "https://tpaypaymentapi.test.loc:8079/v1/Payments/tpay-fkgokd18839",
                         *           "method": "GET",
                         *           "rel": "self"
                         *         },
                         *         {
                         *           "uri": "https://tpaycheckoutweb.test.loc:8078/checkout/tpay-fkgokd18839",
                         *           "method": "REDIRECT",
                         *           "rel": "approval_url"
                         *         }
                         *       ],
                         *       "transactionId": null,
                         *       "httpStatusCode": 200,
                         *       "developerMessage": null,
                         *       "userMessage": null
                         *     }
                         */
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tpay/payments/{payment_id}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** web-complete-payment */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example {{app-key}} */
                    apikey?: string;
                };
                path: {
                    /** @example {{payment-id}} */
                    payment_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "amount": 0.1
                     *     }
                     */
                    "application/json": {
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaymentAmount: {
            /** @enum {string} */
            currency: "GEL" | "USD" | "EUR";
            total: number;
            subTotal?: number;
            tax?: number;
            shipping?: number;
        };
        PaymentResponse: {
            payId: string;
            /** @enum {string} */
            status: "Created" | "Processing" | "Succeeded" | "Failed";
            links: {
                uri: string;
                /** @enum {string} */
                method: "GET" | "POST" | "REDIRECT";
                /** @enum {string} */
                rel: "self" | "approval_url";
            }[];
            transactionId?: string | null;
            httpStatusCode?: number;
            developerMessage?: string | null;
            userMessage?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
